version: 2
jobs:
    build:
        machine: true
        working_directory: ~/node
        environment:
            IMAGE_NAME: ramtek/splendy
        steps:
            - checkout
            - run:
                name: Add environment file
                command: |
                    touch .env
                    echo "MONGO_USER=$MONGO_USER" >> .env
                    echo "MONGO_PASS=$MONGO_PASS" >> .env
                    echo "MONGO_DB=$MONGO_DB" >> .env
                    echo "MONGO_HOST=$MONGO_HOST" >> .env
            - run:
                name: Build Docker image
                command: docker build -t $IMAGE_NAME:latest .
            - run:
                name: Publish Docker Image to Docker Hub
                command: |
                    echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                    docker push $IMAGE_NAME:latest
    deploy:
        machine:
            enabled: true
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "3e:73:c2:e6:e6:2f:2e:9b:5a:37:68:c0:49:f9:31:1e"
            - run: 
                name: Deploy Over SSH
                command: |
                    ssh -v $DROPLET_USER@$DROPLET_IP "~/deploy/deploy_splendy.sh"
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master