driver_path = './chromedriver'
brave_path = 'C:/Program Files (x86)/BraveSoftware/Brave-Browser/Application/brave.exe'
groovin_url = 'https://www.moshtix.com.au/v2/event/groovin-the-moo-townsville-2020/117128'
splendour_url = 'https://www.moshtix.com.au/v2/event/splendour-in-the-grass-2020/119191'
login_url = 'https://www.moshtix.com.au/v2/account/login'